//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yillikizin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class belge
    {
        public int belgeId { get; set; }
        public int personelId { get; set; }
        public string belgeAdi { get; set; }
        public string dosyaYolu { get; set; }
        public System.DateTime yuklemeTarihi { get; set; }
    
        public virtual personel personel { get; set; }
    }
}
