//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yillikizin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class departman
    {
        public int departmanId { get; set; }
        public string departmanName { get; set; }
    }
}
