//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yillikizin.Models
{
    using System;
    using System.Collections.Generic;

    public partial class EmailSettings
    {
        public int Id { get; set; }
        public string RecipientEmails { get; set; }
        public Nullable<System.TimeSpan> SendTime { get; set; }
        public List<EmailSettings> EmailSettingsList { get; set; }
    }
}
