//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yillikizin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GünlükRaporlar
    {
        public int Id { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<decimal> ÇalışmaSüresi { get; set; }
        public Nullable<decimal> FazlaMesaiSüresi { get; set; }
        public Nullable<decimal> EksikCalismaSüresi { get; set; }
    }
}
