//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yillikizin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izin
    {
        public int IzinId { get; set; }
        public int Personelıd { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public string IzinTuru { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> IzinTuruId { get; set; }
    
        public virtual IzinTuru IzinTuru1 { get; set; }
        public virtual personel personel { get; set; }
    }
}
