//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yillikizin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personel()
        {
            this.belge = new HashSet<belge>();
            this.Hareketler = new HashSet<Hareketler>();
            this.Izin = new HashSet<Izin>();
        }
    
        public int id { get; set; }
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string kartno { get; set; }
        public Nullable<int> sicilno { get; set; }
        public string departman { get; set; }
        public string unvan { get; set; }
        public Nullable<System.DateTime> dogumtarih { get; set; }
        public Nullable<System.DateTime> isegiristarih { get; set; }
        public int hakettigi { get; set; }
        public int kullandigi { get; set; }
        public int kalan { get; set; }
        public string resim { get; set; }
        public Nullable<int> departmanId { get; set; }
        public Nullable<int> kullaniciGrupId { get; set; }
        public string kullaniciGrupAdi { get; set; }
        public Nullable<int> VardiyaId { get; set; }
        public string kan { get; set; }
        public string ayakkabino { get; set; }
        public string beden { get; set; }
        public string adres { get; set; }
        public string gsm { get; set; }
        public Nullable<System.DateTime> iscikistarih { get; set; }
        public bool calisma { get; set; } = true; // Default deðer true olarak ayarlandý
                                                  // 

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<belge> belge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hareketler> Hareketler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izin> Izin { get; set; }
        public virtual Vardiya Vardiya { get; set; }
    }
}
