//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yillikizin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelTransaction
    {
        public int Id { get; set; }
        public string Yon { get; set; }
        public string KartNumarasi { get; set; }
        public string TerminalNo { get; set; }
        public System.DateTime Tarih { get; set; }
        public System.TimeSpan Saat { get; set; }
        public int PersonelId { get; set; }
        public string Bilgi { get; set; }
    }
}
