//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yillikizin.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Vardiya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vardiya()
        {
            this.personel = new HashSet<personel>();
        }

        public int VardiyaId { get; set; }
        public string Ad { get; set; }
        public System.TimeSpan CalismaBaslangic { get; set; }
        public System.TimeSpan CalismaBitis { get; set; }
        public System.TimeSpan MesaiBaslangic { get; set; }
        public System.TimeSpan MesaiBitis { get; set; }
        public System.TimeSpan ErkenGelme { get; set; }
        public System.TimeSpan GecGelme { get; set; }
        public System.TimeSpan ErkenCikma { get; set; }
        public System.TimeSpan GecCikma { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> fmOpsiyon { get; set; }
        public Nullable<bool> serbestcalisma { get; set; }
        public Nullable<bool> ErkenMesai { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel> personel { get; set; }
    }
}
